version: '3.8'  # Используйте более новую версию Docker Compose для расширенных возможностей и лучшей совместимости

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  init-minio:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      mc alias set local http://minio:9000 minio minio123 &&
      mc mb -p local/files-uploads || true &&
      echo '✅ Bucket created'
      "
  python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    environment:
      PYTHONUNBUFFERED: "1"
      DATABASE_URL: postgresql://user:password@postgresql:5432/db

  postgresql:
    image: postgres:13-alpine  # Alpine-версия для меньшего размера и лучшей производительности
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  minio-data:
  postgres-data:
