"""add project

Revision ID: 967f89d55f43
Revises: 762a98b784ad
Create Date: 2025-08-02 15:01:59.194562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967f89d55f43'
down_revision: Union[str, Sequence[str], None] = '762a98b784ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('files', sa.Column('project_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('files_user_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_user_id_fkey'), 'files', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('files', 'project_id')
    op.drop_table('projects')
    # ### end Alembic commands ###
